// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// factor_to_integer_bylevel
Rcpp::IntegerVector factor_to_integer_bylevel(Rcpp::IntegerVector factor, std::vector<std::string> levels);
RcppExport SEXP fastercaster_factor_to_integer_bylevel(SEXP factorSEXP, SEXP levelsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type factor(factorSEXP );
        Rcpp::traits::input_parameter< std::vector<std::string> >::type levels(levelsSEXP );
        Rcpp::IntegerVector __result = factor_to_integer_bylevel(factor, levels);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// factor_to_numeric_bylevel
Rcpp::NumericVector factor_to_numeric_bylevel(Rcpp::IntegerVector factor, std::vector<std::string> levels);
RcppExport SEXP fastercaster_factor_to_numeric_bylevel(SEXP factorSEXP, SEXP levelsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type factor(factorSEXP );
        Rcpp::traits::input_parameter< std::vector<std::string> >::type levels(levelsSEXP );
        Rcpp::NumericVector __result = factor_to_numeric_bylevel(factor, levels);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
