# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

factor_to_integer_bylevel <- function(factor, levels) {
    .Call('fastercaster_factor_to_integer_bylevel', PACKAGE = 'fastercaster', factor, levels)
}

factor_to_numeric_bylevel <- function(factor, levels) {
    .Call('fastercaster_factor_to_numeric_bylevel', PACKAGE = 'fastercaster', factor, levels)
}

